[workspace]
resolver = "3"
members = ["parser", "converter", "comparer"]

[workspace.dependencies]
thiserror = "2.0"
byteorder = "1.5"
clap = { version = "4.5", features = ["derive"] }
rstest = "0.26"
